spring:
  application:
    name: ems-reactive   # This name is used to lookup secrets in Vault

  cloud:
    vault:
      uri: http://localhost:8200
      token: myroot       # Use your real token or AppRole in production
      kv:
        enabled: true
        backend: secret   # Default KV backend path

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/emsDB}

  main:
    web-application-type: reactive

server:
  port: 8080
  reactive:
    context-path: /ems

randomuser:
  base-url: https://randomuser.me/api
  enabled: true

github:
  token: ${github.token}
  owner: poojasheela
  repo: ems
  workflow: build.yml
  ref: main
