name: Java CI with Maven


on:
  push:
  workflow_dispatch:
    inputs:
      reason:
        description: 'The reason for manually triggering this workflow'
        required: false
        default: 'Manual trigger via API'

jobs:
  build_and_test:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven (skip tests)
        run: mvn clean package -DskipTests

      - name: Run tests
        run: mvn test
