name: Spring reactive build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
        # Remove built-in healthcheck to avoid 'unhealthy'
        options: "--no-healthcheck"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set environment variables
        run: echo "SPRING_DATA_MONGODB_URI=mongodb://localhost:27017/emsDB" >> $GITHUB_ENV

      # Wait until MongoDB is ready
      - name: Wait for MongoDB
        run: |
          for i in {1..30}; do
            if nc -z localhost 27017; then
              echo "MongoDB is up!"
              break
            fi
            echo "Waiting for MongoDB..."
            sleep 5
          done

      - name: Build with Maven (skip tests)
        run: mvn -B clean package -DskipTests

      - name: Run Tests
        run: mvn test
